# add_newline = false
command_timeout = 5000

[character] 
# success_symbol = "[âœ—](bold yellow)" 
# error_symbol = "[âœ—](bold red)"
success_symbol = "[âœ](bold yellow)" 
error_symbol = "[âœ](bold red)"

[container]
disabled = true

# [battery]
# full_symbol = "âš¡ "
# unknown_symbol = "âš¡ "
# charging_symbol = "âš¡ "
# discharging_symbol = "ğŸ’€ "
# # disabled = false

# [[battery.display]]
# threshold = 100
# style = "white"

[cmd_duration]
min_time = 2_000
format = " took [$duration]($style)"

[aws]
symbol = "îŒ½  "

[c]
symbol = "î˜ "

[directory]
style = "bold 43"
read_only = " ï ½"
truncation_length = 1

[docker_context]
symbol = "ïŒˆ "

[golang]
symbol = "î˜§ "
format = 'via [$symbol]($style)'

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "
format = 'via [$symbol]($style)'

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
# symbol = "îœ˜ "
symbol = "node "
format = 'via [$symbol($version )]($style)'

[package]
# symbol = "ï£– "
symbol = "pkg "

[php]
symbol = "î˜ˆ "

[python]
# symbol = "î˜† "
symbol = "py "
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[ruby]
# symbol = "îˆ¾ "
symbol = "ruby "
format = "via [$symbol($version )]($style)"

[rust]
symbol = "ğŸ¦€ "
format = "via [$symbol($version )]($style)"

[bun]
symbol = "ğŸ "
format = "via [$symbol($version )]($style)"


[git_branch]
symbol = ""
style = "bold 35"
# style = "bold 105"
# symbol = "ï˜ "

# [git_commit]
# commit_hash_length = 8
# style = "bold white"

[git_metrics]
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
up_to_date = "âœ“"
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'
untracked = "?"
style = "bold 35"
# conflicted = "âš”ï¸"
# ahead = "â‡¡"
# behind = "ğŸ¢"
# diverged = "ğŸ”±"
# stashed = "ğŸ“¦"
# #modified = "!"
# staged = "ğŸ—ƒï¸"
# renamed = "ğŸ“›"
# deleted = "ğŸ—‘ï¸"
# format = "$all_status$ahead_behind"
# disabled = true


# [time]
# time_format = "%a, %b %d, %Y | %I:%M%P ï¸"
# time_format = "%a, %I:%M%P"
# format = "$time($style) "
# style = "bright-white"
# disabled = false
